### ISSUE TITLE
Algolia is not working on Nuxt

### ISSUE THREAD

**Issue by typhoon11** [nuxt-modules/algolia#122] opened 2023-01-03 12:21 UTC
### Version

@nuxtjs/algolia: 1.4.0
nuxt: 3.0.0

### Reproduction Link

![image](https://user-images.githubusercontent.com/66431066/210356331-f5999106-2957-4037-9c7c-b0752e621596.png)

**Comment by Baroshem** [comment] 2023-01-03 12:36
Hey,

have you followed this docs https://algolia.nuxtjs.org/advanced/vue-instantsearch?

**Comment by typhoon11** [comment] 2023-01-03 14:05
> Hey,
> 
> have you followed this docs https://algolia.nuxtjs.org/advanced/vue-instantsearch?

Yeah did that all even install that vueinstant search package as it was not download by algolia

**Comment by Baroshem** [comment] 2023-01-03 15:58
Could you paste here your configuration of the module and how do you use it in the Vue component?

**Comment by typhoon11** [comment] 2023-01-03 17:18
> Could you paste here your configuration of the module and how do you use it in the Vue component?

nuxt.config.ts
```ts
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/algolia'
  ]
  algolia: {
          apiKey: 'M91b29bc3b270e50cd3d549xxxxxxx,
          applicationId: 'W0FRE10Z7J',
          lite: true,
          cache: true,
          instantSearch: {
              theme: 'algolia'
          }
      }
})
 ```
 DashHeader.vue (Component)
 ```html
 <ais-instant-search :index-name="indexName" :search-client="algolia">
        <ais-search-box />
        <ais-hits />
</ais-instant-search>
<script>
    import { AisInstantSearch, AisSearchBox, AisHits } from 'vue-instantsearch/vue3/es/index.js'
    export default ({
      async setup() {
            const indexName = 'module_search' 
            const algolia = useAlgoliaRef('')

            return {
                indexName,
                algolia
            }
        },
    })
</script>
```

**Comment by Baroshem** [comment] 2023-01-03 19:32
This is really strange. I have just copied the code into example nuxt 3 project and it works:

Component: 
```vue
<template>
  <div>
    <ais-instant-search :index-name="indexName" :search-client="algolia">
      <ais-search-box />
      <ais-hits />
    </ais-instant-search>
  </div>
</template>

<script setup lang="ts">
import { AisInstantSearch, AisSearchBox, AisHits } from 'vue-instantsearch/vue3/es/index.js'
const indexName = 'dxp'
const algolia = useAlgoliaRef()
</script>
```

Configuration:
```ts
export default defineNuxtConfig({
  modules: [
    [
      "@nuxtjs/algolia",
      {
        apiKey: process.env.ALGOLIA_SEARCH_API_KEY,
        applicationId: process.env.ALGOLIA_APP_ID,
        instantSearch:{
          theme: 'algolia'
        }
      },
    ],
  ],
});
```

Result in the browser:
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/37120330/210427967-ead23c33-858d-4186-9ab5-46af94225017.png">

Could you try to just copy/paste my code and see if it works for you that way? Maybe some typo somewhere? If it wont work, could you provide a reproduction link? I would be happy to investigate it more once I will have a reproducible project :)

**Comment by typhoon11** [comment] 2023-01-03 19:36
> This is really strange. I have just copied the code into example nuxt 3 project and it works:
> 
> Component: 
> ```vue
> <template>
>   <div>
>     <ais-instant-search :index-name="indexName" :search-client="algolia">
>       <ais-search-box />
>       <ais-hits />
>     </ais-instant-search>
>   </div>
> </template>
> 
> <script setup lang="ts">
> import { AisInstantSearch, AisSearchBox, AisHits } from 'vue-instantsearch/vue3/es/index.js'
> const indexName = 'dxp'
> const algolia = useAlgoliaRef()
> </script>
> ```
> 
> Configuration:
> ```ts
> export default defineNuxtConfig({
>   modules: [
>     [
>       "@nuxtjs/algolia",
>       {
>         apiKey: process.env.ALGOLIA_SEARCH_API_KEY,
>         applicationId: process.env.ALGOLIA_APP_ID,
>         instantSearch:{
>           theme: 'algolia'
>         }
>       },
>     ],
>   ],
> });
> ```
> 
> Result in the browser:
> <img width="1672" alt="image" src="https://user-images.githubusercontent.com/37120330/210427967-ead23c33-858d-4186-9ab5-46af94225017.png">
> 
> Could you try to just copy/paste my code and see if it works for you that way? Maybe some typo somewhere? If it wont work, could you provide a reproduction link? I would be happy to investigate it more once I will have a reproducible project :)

Sure i will try your code tomorrow and see and will also try to reinstall the algolia package once again and also if that doesn't work will share a stackblitz link. Btw I am assuming the index name can be anything right?

**Comment by Baroshem** [comment] 2023-01-03 19:41
It should be the name of the index in Algolia Dashboard. 

Let me know about the results so that I can help you resolve these issues 🙂

**Comment by typhoon11** [comment] 2023-01-04 05:14
> This is really strange. I have just copied the code into example nuxt 3 project and it works:
> 
> Component:
> 
> ```
> <template>
>   <div>
>     <ais-instant-search :index-name="indexName" :search-client="algolia">
>       <ais-search-box />
>       <ais-hits />
>     </ais-instant-search>
>   </div>
> </template>
> 
> <script setup lang="ts">
> import { AisInstantSearch, AisSearchBox, AisHits } from 'vue-instantsearch/vue3/es/index.js'
> const indexName = 'dxp'
> const algolia = useAlgoliaRef()
> </script>
> ```
> 
> Configuration:
> 
> ```ts
> export default defineNuxtConfig({
>   modules: [
>     [
>       "@nuxtjs/algolia",
>       {
>         apiKey: process.env.ALGOLIA_SEARCH_API_KEY,
>         applicationId: process.env.ALGOLIA_APP_ID,
>         instantSearch:{
>           theme: 'algolia'
>         }
>       },
>     ],
>   ],
> });
> ```
> 
> Result in the browser: <img alt="image" width="1672" src="https://user-images.githubusercontent.com/37120330/210427967-ead23c33-858d-4186-9ab5-46af94225017.png">
> 
> Could you try to just copy/paste my code and see if it works for you that way? Maybe some typo somewhere? If it wont work, could you provide a reproduction link? I would be happy to investigate it more once I will have a reproducible project :)

Here is the reproduction link: https://stackblitz.com/edit/nuxt-starter-azgjp4?file=nuxt.config.ts

**Comment by Baroshem** [comment] 2023-01-04 07:10
I know where the problem is. 

In your example, you are not using a [script setup](https://vuejs.org/api/sfc-script-setup.html) approach which will automatically register components. So, in your case you need to register them as following:

```vue
<template>
  <div>
    <ais-instant-search :index-name="indexName" :search-client="algolia">
      <ais-search-box />
      <ais-hits />
    </ais-instant-search>
  </div>
</template>
<script>
    import { AisInstantSearch, AisSearchBox, AisHits } from 'vue-instantsearch/vue3/es/index.js'
    export default {
        components: {
          AisInstantSearch,
          AisSearchBox,
          AisHits
        },
        async setup() {
            const indexName = 'test_index' 
            const algolia = useAlgoliaRef()

            return {
                indexName,
                algolia
            }
        }
    }
</script>
```

If you do so, you will have following result in stackblitz and your project:
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/37120330/210502217-4c0bddd9-d958-44c2-948c-e78819f168f9.png">

Let me know if that worked for you.

**Comment by typhoon11** [comment] 2023-01-04 07:33
> I know where the problem is.
> 
> In your example, you are not using a [script setup](https://vuejs.org/api/sfc-script-setup.html) approach which will automatically register components. So, in your case you need to register them as following:
> 
> ```
> <template>
>   <div>
>     <ais-instant-search :index-name="indexName" :search-client="algolia">
>       <ais-search-box />
>       <ais-hits />
>     </ais-instant-search>
>   </div>
> </template>
> <script>
>     import { AisInstantSearch, AisSearchBox, AisHits } from 'vue-instantsearch/vue3/es/index.js'
>     export default {
>         components: {
>           AisInstantSearch,
>           AisSearchBox,
>           AisHits
>         },
>         async setup() {
>             const indexName = 'test_index' 
>             const algolia = useAlgoliaRef()
> 
>             return {
>                 indexName,
>                 algolia
>             }
>         }
>     }
> </script>
> ```
> 
> If you do so, you will have following result in stackblitz and your project: <img alt="image" width="1284" src="https://user-images.githubusercontent.com/37120330/210502217-4c0bddd9-d958-44c2-948c-e78819f168f9.png">
> 
> Let me know if that worked for you.

Thanks a lot that worked perfectly

**Comment by Baroshem** [comment] 2023-01-04 08:15
Ok cool, closing the issue then.

**Closed by Baroshem** 2023-01-04 08:15 UTC
Labels: bug
