### ISSUE TITLE
Configuring via .env variables on Nuxt 3

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt-modules/algolia#84] opened 2022-08-06 11:06 UTC
### Version

@nuxtjs/algolia: 1.1.1
nuxt: 3.0.0-rc.6

### Steps to reproduce

- Add Algolia to Nuxt 3 project
- Configure it via `env` variables

### What is happening?
```js
algolia: {
    applicationId: process.env.ALGOLIA_APP_ID ?? 'applicationId',
    apiKey: process.env.ALGOLIA_API_KEY ?? 'apiKey',
  },
  ```
  When starting a project error is thrown `Cannot destructure property 'applicationId' of '__vite_ssr_import_0__.useRuntimeConfig(...).algolia' as it is undefined.`
  
  Not sure if this has something to do with #81 or #63 but considering the example in the playground, this should work

**Comment by Baroshem** [comment] 2022-08-06 15:30
Hey @Lexpeartha 

Could you try to rebuild your project or and remove node modules?

I am using env variables in module repo, demo projects, tutorials, and many more so this issue seems wuite strange

**Comment by Lexpeartha** [comment] 2022-08-06 19:33
I was running nuxt 3 edge version, but down-graded it to rc 6 and issue was still there
I did delete both node_modules and .nuxt, but it didn't do anything

**Comment by Baroshem** [comment] 2022-08-07 14:00
@Lexpeartha 

Could you please create a reproduction repository in Stackblitz? I tried it once again and was not able to reproduce it.

**Comment by Lexpeartha** [comment] 2022-08-07 16:38
Well... I can't reproduce it now since it started working for my project as well 🤷🏽‍♂️ 
Idrk what that was, but it seems to work alright now, thanks

**Comment by Baroshem** [comment] 2022-08-08 05:14
I see.

Thank you for testing it out. I hope the module will work for you kow without any issues. 

Happy coding! 😃

**Comment by fmarcheski** [comment] 2022-08-16 16:27
I am seeing this issue on **1.1.1**.
When I roll back to **1.1.0**, it works fine.

Running Nuxt 3.0.0-rc.8

**Comment by Lexpeartha** [comment] 2022-08-16 19:58
@Baroshem Not sure what might be causing the problem to appear again, but it would be great if you could update `@nuxt/kit` dependency since nuxt 3 in newer releases migrated to vite 3, so that might have some impact?

**Comment by Baroshem** [comment] 2022-08-18 09:22
@Lexpeartha @fmarcheski 

Yes, the update to the newest version of nuxt  and nuxt/ki is a planned feature. I want to release it next week preferably with #83 as a 1.2.0. I just need to test some things out to not cause breaking changes for your projects :)

**Comment by podlebar** [comment] 2022-08-19 08:23
i can confirm this bug.. the solution is to move the algolia config to `runtimeConfig.public` and remove it from the general config. If you don't have any public runtimeConfig it works fine as described in the docs.  

Works:
```
export default defineNuxtConfig({
  modules: ['@nuxtjs/algolia'],

  runtimeConfig: {
    FOO: process.env.FOO,
    public: {
      algolia: {
        apiKey: "12345678",
        applicationId: "123",
        instantSearch: true
      },
    }
  }
})
```

Fails:
```
export default defineNuxtConfig({
  modules: ['@nuxtjs/algolia'],

  runtimeConfig: {
    FOO: process.env.FOO,
    public: {
      anyKey: '123'
    }
  },
  algolia: {
     apiKey: "12345678",
     applicationId: "123",
     instantSearch: true
  },
})
```

**Comment by Lexpeartha** [comment] 2022-09-30 14:47
Closing an issue since everything seems to work fine in newer nuxt release candidates 👍🏽

**Comment by cfab** [comment] 2022-10-01 08:14
I still have the error on RC 11 after having destroyed node_modules and .nuxt...
[nuxt] [request error] [unhandled] [500] Cannot destructure property 'applicationId' of '__vite_ssr_import_0__.useRuntimeConfig(...).algolia' as it is undefined.

**Comment by Baroshem** [comment] 2022-10-01 11:14
@cfab 

I would say then that this issue may be caused by the Nuxt itself rather than the module but I will investigate on my side. Have you tried modifying the module code in node_modules to see if it makes a difference?

**Comment by cfab** [comment] 2022-10-03 03:54
Well, I wouldn't dare...  ;-)
Not sure what to modify anyway !
But thanks.

**Comment by Baroshem** [comment] 2022-10-03 15:57
Folks, 

The issue is caused when you have both algolia object and runtimeConfig.public both registered in nuxt.config.ts file.

I will release a fix today to fix this issue.

**Comment by Baroshem** [comment] 2022-10-03 16:28
Should be working now with 1.1.4 version

**Comment by Lexpeartha** [comment] 2022-10-03 18:51
> The issue is caused when you have both algolia object and runtimeConfig.public both registered in nuxt.config.ts file.

I'm beyond curious about how you've figured that out 🤯

**Comment by Baroshem** [comment] 2022-10-04 09:50
Guys, I am closing the issue as it was tested already in a few Nuxf 3 apps with public runtime config. If this error occurs again, please reopen.

**Closed** 2022-10-04 09:50 UTC
Labels: bug
